#!/usr/bin/env python3
"""Fix flextable OOXML issues that cause Word 'unreadable content' warnings.

Problems fixed:
1. Redundant namespace declarations on descendant elements generated by
   flextable (already declared on root <w:document>).
2. Duplicate leading <w:pPr> blocks in <w:p> elements.
3. Missing <w:tblStyle>, <w:tblW>, and <w:tblLook w:val> in flextable table
   properties, which become invalid when Quarto nests flextable inside a
   Pandoc wrapper table (triggered by label: tbl-*).
4. Flextable row-height directives (<w:trHeight>) not present in standard
   Pandoc output.
5. No-op run formatting (<w:i val="false">, <w:b val="false">, etc.)
   frequently emitted by flextable.
6. Flextable-only paragraph attributes (firstLine="0", pBdr, spacing, ind)
   that Word strips on repair.
7. Missing trailing <w:p/> after nested tables inside wrapper cells, required
   by OOXML spec (the last block-level element in a <w:tc> must be a <w:p>).
"""

import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path


PARAGRAPH_RE = re.compile(r"<w:p(?:\s[^>]*)?>.*?</w:p>", re.DOTALL)
PPR_BLOCK_RE = re.compile(r"<w:pPr\b[^>]*>.*?</w:pPr>", re.DOTALL)
TBLPR_RE = re.compile(r"<w:tblPr>(.*?)</w:tblPr>", re.DOTALL)


def fix_document_xml(xml_bytes: bytes) -> bytes:
    """Fix the word/document.xml content."""
    text = xml_bytes.decode("utf-8")

    # --- Fix 1: Strip redundant namespace declarations from descendant elements ---
    # Flextable adds xmlns:w, xmlns:r, xmlns:wp, etc. on every <w:tbl> and <w:r>,
    # duplicating what's already on <w:document>. It also adds xmlns:w14 which is
    # never used. We only remove declarations whose prefix+URI already appear on the
    # root element, preserving genuinely needed ones (e.g. xmlns:a14, xmlns:asvg on
    # image elements).

    # Parse root element's namespace declarations
    doc_start = text.find("<w:document")
    if doc_start == -1:
        return xml_bytes

    doc_end = text.find(">", doc_start)
    if doc_end == -1:
        return xml_bytes
    doc_end += 1
    root_tag = text[doc_start:doc_end]
    root_ns = dict(re.findall(r'xmlns:(\w+)="([^"]*)"', root_tag))

    # Also add xmlns:w14 to root so child declarations become redundant.
    # w14 is declared 364x by flextable but never actually referenced by any
    # element or attribute; adding it to root is harmless and lets us strip
    # all child-level copies.
    if "w14" not in root_ns:
        w14_uri = "http://schemas.microsoft.com/office/word/2010/wordml"
        root_tag = root_tag.replace(
            ">",
            f' xmlns:w14="{w14_uri}">',
            1,
        )
        root_ns["w14"] = w14_uri

    # Build patterns for redundant declarations only
    redundant_patterns = []
    for prefix, uri in root_ns.items():
        escaped_uri = re.escape(uri)
        redundant_patterns.append(
            rf'\s+xmlns:{re.escape(prefix)}="{escaped_uri}"'
        )
    if redundant_patterns:
        redundant_re = re.compile("|".join(redundant_patterns))
        body = text[doc_end:]
        body = redundant_re.sub("", body)
        text = text[:doc_start] + root_tag + body

    # --- Fix 2: Keep only the last duplicate leading <w:pPr> in each paragraph ---
    # A paragraph can start with multiple adjacent pPr blocks:
    # <w:p><w:pPr>...</w:pPr><w:pPr>...</w:pPr>...
    # We keep the last one (typically flextable's richer settings) and drop
    # earlier duplicates. Processing paragraph-by-paragraph avoids cross-tag
    # over-matching that can corrupt XML.
    def dedupe_paragraph_ppr(match):
        paragraph = match.group(0)
        open_end = paragraph.find(">") + 1
        close_start = paragraph.rfind("</w:p>")
        if open_end <= 0 or close_start < 0:
            return paragraph

        inner = paragraph[open_end:close_start]
        pos = 0
        ws = re.match(r"\s*", inner[pos:])
        if ws is not None:
            pos += ws.end()

        blocks = []
        while True:
            ppr = PPR_BLOCK_RE.match(inner, pos)
            if ppr is None:
                break
            blocks.append((ppr.start(), ppr.end(), ppr.group(0)))
            pos = ppr.end()
            ws = re.match(r"\s*", inner[pos:])
            if ws is not None:
                pos += ws.end()

        if len(blocks) < 2:
            return paragraph

        first_start = blocks[0][0]
        last_end = blocks[-1][1]
        deduped_inner = inner[:first_start] + blocks[-1][2] + inner[last_end:]
        return paragraph[:open_end] + deduped_inner + paragraph[close_start:]

    text = PARAGRAPH_RE.sub(dedupe_paragraph_ppr, text)

    # --- Fix 3: Normalize flextable inner table properties ---
    # Flextable-generated inner tables can omit <w:tblStyle> and w:tblLook/@w:val.
    # Word sometimes flags such documents as containing unreadable content.
    # We align these with Pandoc-style table properties used in the same document.
    def normalize_tblpr(match):
        inner = match.group(1)

        if "<w:tblStyle" not in inner:
            # Match Pandoc defaults used by neighboring wrapper tables.
            inner = (
                '<w:tblStyle w:val="Table" />'
                '<w:tblW w:type="pct" w:w="5000" />'
                + inner
            )

        def normalize_tbllook(tbl_look_match):
            attrs_text = tbl_look_match.group(1)
            attrs = dict(re.findall(r'([A-Za-z0-9_:-]+)="([^"]*)"', attrs_text))

            # Compute table-look bitmask from flags.
            # firstRow=0x0020, lastRow=0x0040, firstColumn=0x0080, lastColumn=0x0100,
            # noHBand=0x0200, noVBand=0x0400.
            mask = 0
            if attrs.get("w:firstRow") == "1":
                mask |= 0x0020
            if attrs.get("w:lastRow") == "1":
                mask |= 0x0040
            if attrs.get("w:firstColumn") == "1":
                mask |= 0x0080
            if attrs.get("w:lastColumn") == "1":
                mask |= 0x0100
            if attrs.get("w:noHBand") == "1":
                mask |= 0x0200
            if attrs.get("w:noVBand") == "1":
                mask |= 0x0400

            computed_val = f"{mask:04X}"
            if "w:val" in attrs:
                attrs_text = re.sub(
                    r'\bw:val="[^"]*"',
                    f'w:val="{computed_val}"',
                    attrs_text,
                    count=1,
                )
            else:
                attrs_text = attrs_text + f' w:val="{computed_val}"'
            return f"<w:tblLook{attrs_text}/>"

        inner = re.sub(
            r"<w:tblLook\b([^>]*)/>",
            normalize_tbllook,
            inner,
            flags=re.DOTALL,
        )

        return f"<w:tblPr>{inner}</w:tblPr>"

    text = TBLPR_RE.sub(normalize_tblpr, text)

    # --- Fix 4: Remove flextable row-height directives ---
    # Flextable emits <w:trHeight w:val="360" w:hRule="auto"/> for many rows.
    # Word rewrites/removes these on successful re-save, and no-flextable output
    # does not contain them. Strip them proactively.
    text = re.sub(r"<w:trHeight\b[^>]*/>", "", text)
    text = re.sub(r"<w:trPr>\s*</w:trPr>", "", text)

    # --- Fix 5: Remove no-op run formatting frequently emitted by flextable ---
    # These are redundant in OOXML and heavily rewritten by Word on recovery.
    # Stripping them reduces the amount of recovery Word needs to perform.
    text = re.sub(r"<w:i\b[^>]*\bw:val=\"false\"[^>]*/>", "", text)
    text = re.sub(r"<w:b\b[^>]*\bw:val=\"false\"[^>]*/>", "", text)
    text = re.sub(r"<w:strike\b[^>]*\bw:val=\"false\"[^>]*/>", "", text)
    text = re.sub(r"<w:u\b[^>]*\bw:val=\"none\"[^>]*/>", "", text)
    text = re.sub(r"<w:rPr>\s*</w:rPr>", "", text)

    # --- Fix 6: Drop flextable-only paragraph attrs that Word strips on repair ---
    # These appear in table-cell paragraphs and are absent in no-flextable output.
    # Word removes them during recovery, so we normalize proactively.
    text = re.sub(r'\s+w:firstLine="0"', "", text)
    text = re.sub(r'\s+w:firstLineChars="0"', "", text)
    text = re.sub(r'\s+w:line="240"', "", text)
    text = re.sub(r"<w:pBdr\b[^>]*>.*?</w:pBdr>", "", text, flags=re.DOTALL)
    text = re.sub(r"<w:ind\b[^>]*/>", "", text)
    text = re.sub(
        r'<w:spacing\b[^>]*\bw:after="100"[^>]*\bw:before="100"[^>]*/>',
        "",
        text,
    )
    text = re.sub(r"<w:pPr>\s*</w:pPr>", "", text)

    # --- Fix 7: Add trailing <w:p/> after nested tables inside wrapper cells ---
    # OOXML requires that the last block-level element in a <w:tc> is a <w:p>.
    # When Quarto wraps a flextable in a caption wrapper table (triggered by
    # label: tbl-*), the inner <w:tbl> ends the cell without a trailing paragraph.
    # Word flags this as "unreadable content".
    text = re.sub(
        r"(</w:tbl>)(\s*(?:<w:bookmarkEnd\b[^>]*/>)?\s*</w:tc>)",
        r"\1<w:p/>\2",
        text,
    )

    return text.encode("utf-8")


def fix_docx(input_path: str, output_path: str | None = None) -> None:
    """Fix a .docx file in-place or to a new path."""
    input_path = Path(input_path)
    if output_path is None:
        output_path = input_path
    else:
        output_path = Path(output_path)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_out = Path(tmpdir) / "fixed.docx"

        with zipfile.ZipFile(input_path, "r") as zin:
            with zipfile.ZipFile(tmp_out, "w", zipfile.ZIP_DEFLATED) as zout:
                for item in zin.infolist():
                    data = zin.read(item.filename)
                    if item.filename == "word/document.xml":
                        data = fix_document_xml(data)
                    zout.writestr(item, data)

        shutil.move(str(tmp_out), str(output_path))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.docx> [output.docx]")
        sys.exit(1)

    in_file = sys.argv[1]
    out_file = sys.argv[2] if len(sys.argv) > 2 else None
    fix_docx(in_file, out_file)
    target = out_file or in_file
    print(f"Fixed: {target}")
